### ISSUE TITLE
go get github.com/shyiko/kubetpl fails in module mode

### ISSUE THREAD

**Issue by ConradIrwin** [shyiko/kubetpl#29]
This module depends on github.com/Sirupsen/logrus, which has been renamed to github.com/sirupsen/logrus.

This causes installation to fail in go module mode with:
```
go: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
```

We can work around this by setting:

```
replace github.com/Sirupsen/logrus v1.6.0 => github.com/sirupsen/logrus v1.6.0
```

in our `go.mod`, but it would be better to update this library to reference the new name directly.

**Comment by ConradIrwin** [comment]
I have sent a pull request that addresses this (#30). I am also happy to send another that migrates from glide to go modules if that would be interesting to you.

**Comment by shyiko** [comment]
Thank you once again for the PR, @ConradIrwin. If you send a PR for go.mod I'll definitely merge it in.
