### ISSUE TITLE
Support for `data-from-env-file`

### ISSUE THREAD

**Issue by frankh** [shyiko/kubetpl#3]
similar to the `kubectl create configmap ... --from-file=... --from-file=... --from-file` use case being replaced by `kubetpl/data-from-file`, I feel like there should be `kubetpl/data-from-env-file` for the equivalent `kubectl create configmap ... --from-env-file=... --from-env-file=... --from-env-file` use case

**Comment by shyiko** [comment]
Hi Frank. Added in [0.5.0](https://github.com/shyiko/kubetpl/blob/master/CHANGELOG.md#050---2018-04-29). :tada:
