### ISSUE TITLE
gpg: can't open signed data `/usr/local/bin/kubetpl'

### ISSUE THREAD

**Issue by stafot** [shyiko/kubetpl#7]
While running the verified installation, verification fails.

Error I am getting 
```
gpg: can't open signed data `/usr/local/bin/kubetpl'
gpg: can't hash datafile: file open error
```
Previous steps are successful.

**Comment by shyiko** [comment]
Hi. 

Please check that /usr/local/bin/kubetpl is a binary and kubetpl.asc contains PGP signature (you can use `file` for that, e.g. `file /usr/local/bin/kubetpl && file kubetpl.asc`). My guess would be that one of them is corrupted (you might want to check that your terminal is not escaping $ on copy/paste (iTerm is known to do that)). 

I've just tried to [reinstall kubetpl](https://github.com/shyiko/kubetpl#macos--linux) and everything seems to be in order.

What's your OS/`gpg --version`?

**Comment by stafot** [comment]
@shyiko Thanks for your answer. 
```
/usr/local/bin/kubetpl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped
kubetpl.asc: PGP signature Signature (old)
```

OS/gpg : `Ubuntu`/ ```gpg (GnuPG) 1.4.20
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.```

The non-`gpg` installation works fine.

**Comment by shyiko** [comment]
I see. Try upgrading gpg to >= 2. Most probably you're hitting some weird gpg version incompatibility issue.
